[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "chromium", "xvfb-run"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "xvfb-run -a python3 monitor_bot.py"
