[phases.setup]
nixPkgs = ["python3", "chromium", "xvfb-run"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "xvfb-run -a python3 monitor_bot.py"
